import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Next js website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.navbar}>
        <ul>
          <a href="/index"><li>Home</li></a>
          <a href="/about"><li>About</li></a>
          <a href="/contact"><li>Contact</li></a>
          <a href="/blogs"><li>Blog</li></a>
        </ul>
      </nav>
      <div className={styles.image}>
        <Image src="/demo.jpg" width="1300" height="510" className={styles.demo}></Image>
        <h1 className={styles.heading1}>THE REDCLIFFE STORY</h1>
        <p className={styles.heading2}>Making Diagnostics Accessible to people</p>

      </div>

      <div className={styles.maindiv}>
        <div className={styles.side1}><Image src="/about.png" width="550" height="350" className={styles.image2}></Image></div>
        <div className={styles.side2}><h1>How We Started</h1>
          <p className={styles.paragraph}>We started our journey in 2018 driven by a strong sense of <br />
             purpose & very important question in our minds How can <br />
             we make quality healthcare accessible to each and every <br />
             person across our diverse country.</p>
        </div>
      </div>
      
      
    </>
  );
}
