import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Next js website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  

      <div className={styles.image}>
        <Image src="/demo.jpg" width="1300" height="510" className={styles.demo}></Image>
        <h1 className={styles.heading1}>THE REDCLIFFE STORY</h1>
        <p className={styles.heading2}>Making Diagnostics Accessible to people</p>

      </div>

      <div className={styles.maindiv}>
        <div className={styles.side1}><Image src="/about.png" width="550" height="350" className={styles.image2}></Image></div>
        <div className={styles.side2}><h1>How We Started</h1>
          <p className={styles.paragraph}>We started our journey in 2018 driven by a strong sense of <br />
            purpose & very important question in our minds How can <br />
            we make quality healthcare accessible to each and every <br />
            person across our diverse country.</p>
        </div>
      </div>
      <div className={styles.maindivpart2}>
        <div className={styles.side3}>
          <h1 className={styles.heading3}>Defining The Problem</h1>
          <p className={styles.paragraph2}>We witnessed stark realities both in urban and rural areas <br />
            right from the issue of affordability to the problem of  <br />
            accessibility. This innate desire to improve overall well-being <br />
            of people by giving them accurate diagnostics, led to the <br />
            birth of Redcliffe Labs.</p>
        </div>
        <div className={styles.side4}><Image src="/third.png" width="550" height="350" className={styles.image3}></Image>

        </div>
      </div>

      <div className={styles.maindiv4}>
        <div className={styles.side4}><Image src="/forth.png" width="550" height="350" className={styles.image4}></Image></div>
        <div className={styles.side5}><h1 className={styles.heading5}>Creating a Pan-India Dx revolution</h1>
          <p className={styles.paragraph4}>Entwined with the philosophy of making diagnostics, the first <br />
            step, towards preventive health & disease management, <br />
            weve been able to cater to 2.5 million Indians in a short <br />
            span of 4 years.</p>
        </div>
      </div>

      <div className={styles.image5}>
        <Image src="/five.jpg" width="1300" height="510" className={styles.demo5}></Image>
        <h1 className={styles.heading6}>THE REDCLIFFE STORY</h1>
        <p className={styles.heading7}>At Redcliffe Labs, we ve built a comprehensive portfolio approach both with routine and <br />
          specialized test menus with advanced testing labs all over India. We cater to all diagnostic <br />
          needs, thereby contributing to the health needs of millions of patients.</p>

        <div>
          <div className={styles.icon1}>  <Image src="/ICON1.png" width="80" height="80" className={styles.imageicon}></Image></div>
          <h1 className={styles.heading8}>Digital-first <br />
            approach  </h1>
          <div className={styles.icon2}>  <Image src="/ICON2.png" width="80" height="80" className={styles.imageicon2}></Image></div>
          <h1 className={styles.heading9}>Accurate Reports <br />
            within 24 Hrs </h1>
          <div className={styles.icon3}>  <Image src="/ICON3.png" width="80" height="80" className={styles.imageicon3}></Image></div>
          <h1 className={styles.heading10}>On-demand 1-hour <br />
            home collection </h1>

          <div className={styles.handmain}>
            <div className={styles.hand1}>
              <Image src="/five.png" height="200" width="200" className={styles.fiveimg}></Image>
            </div>
            <div className={styles.hand2}>
              <h1 className={styles.hand2part1}>OUR VISION</h1>
              <p className={styles.hand2part2}>High Quality and Affordable Diagnostics Platform for <br />
                Bharat - Empowering Health, Impacting Lives.</p>

              <h1 className={styles.hand2part3}>OUR MISSION</h1>
              <p className={styles.hand2part4}>To serve 500 million Indians by 2030</p>
            </div>
          </div>

          <div className={styles.secondlastb}>
            <Image src="/five.png" height="300" width="300" className={styles.siximg}></Image>
            <h1 className={styles.sixheading}>OUR IMPACT DIFFERENTIATORS</h1>
            <div className={styles.siximg1}>
              <Image src="/six12.png" height="20" width="40" className={styles.siximage}></Image>
              <h1 className={styles.sixheading1}>Technology Integration</h1>
              <p className={styles.sixpra}>From tamper-proof sample <br />
                collection to accurate <br />
                reports, we deploy  <br />
              </p>
            </div>
            <div className={styles.siximg2}>
              <Image src="/six11.png" height="20" width="30" className={styles.siximg11}></Image>
              <h1 className={styles.sixheading11}>Accessible to all</h1>
              <p className={styles.sixpra2}>Our focus is to make <br />
                diagnostics accessible <br />
                to everyone from cities</p>

            </div>
            <div className={styles.siximg3}>
              <Image src="/six13.png" height="20" width="30" className={styles.siximg12}></Image>
              <h1 className={styles.sixheading13}>Robust Interfaces</h1>
              <p className={styles.paragraph131}>Right from booking the test to <br />
                making reports available to <br />
                resolve other queries in no</p>
            </div>
          </div>
          <div className={styles.second2}>
            <h1 className={styles.second3}>REDCLIFFE LABS QUALITY ASSURE</h1>
            <p className={styles.second4}>
              Our internal quality benchmarks ensure that accuracy is maintained at every step of testing of <br />
              samples. Right from the bag in which sample is transported to the six-sigma processes, these <br />
              quality standards are followed stringently to ensure test report accuracy and reliability of <br />
              highest standard.
            </p>
          </div>


        </div>


        <div className={styles.mainp}>
          <div className={styles.mainp1} >
            <div className={styles.p1rotat}><Image src="/p1.png" height="20" width="49" className={styles.p1img}></Image></div>
            <h1 className={styles.p1heading}>NABL Accredited & ISO Certified</h1>
            <p className={styles.p1paragraph}>All our labs, National & Regional <br />
              Reference are accredited by NABL. <br />
              We follow guidelines laid down by <br />
              the International Standard <br />
              ISO15189:2012.</p>
          </div>
          <div className={styles.mainp2}>
            <div className={styles.p1rotat}><Image src="/p2.png" height="20" width="49" className={styles.p1img}></Image></div>
            <h1 className={styles.p1heading}>Six-Sigma <br /> Processes</h1>
            <p className={styles.p1paragraph}>Two levels of quality control are <br /> performed at the peak hour <br />
              followed by one level every eight hours <br />
              The quality standards are integrated in all phases: pre- <br />
              analytical, analytical, and post- <br />
              analytical.</p>
          </div>
          <div className={styles.mainp3}>
            <div className={styles.p1rotat}><Image src="/p3.png" height="20" width="49" className={styles.p1img}></Image></div>
            <h1 className={styles.p1heading}>Innovative <br /> Patented <br /> Technology</h1>
            <p className={styles.p1paragraph}>Implementation of real-time <br />
              temperature monitoring technology <br />
              ensures sample integrity for <br />
              accurate test results.</p>
          </div>

        </div>
        <div className={styles.maincore}>

          <div className={styles.core1}>
            <Image src="/happycustomer.png" height="50" width="50" className={styles.coreimg1}></Image>
            <h1 className={styles.coreheading1}>CUSTOMER FIRST</h1>
          </div>
          <div className={styles.core2}>
            <Image src="/quality.png" height="50" width="50" className={styles.coreimg1}></Image>
            <h1 className={styles.coreheading2}>QUALITY</h1>
          </div>
          <div className={styles.core3}>

            <Image src="/integrity.png" height="50" width="50" className={styles.coreimg1}></Image>
            <h1 className={styles.coreheading2}>INTEGRITY</h1>
          </div>
          <div className={styles.core4}>
            <Image src="/sustainability.png" height="50" width="50" className={styles.coreimg1}></Image>
            <h1 className={styles.coreheading4}>SUSTAINABILITY</h1>
          </div>
          <div className={styles.core5}>
            <Image src="/efficiency.png" height="50" width="50" className={styles.coreimg1}></Image>
            <h1 className={styles.coreheading5}>EFFICIENCY</h1>
          </div>
          <div className={styles.core6}>
            <Image src="/respect.png" height="50" width="50" className={styles.coreimg1}></Image>
            <h1 className={styles.coreheading6}>RESPECT</h1>
          </div>
        </div>

      </div>
      <h1 className={styles.headingmain}>OUR CORE VALUES</h1>

      <div className={styles.mainlastbanner}>
      
        <div className={styles.lastbanner1}>
          <h1 className={styles.lasth1}>Redcliffe <br /> labs </h1>
          <p className={styles.lastp1}>Redcliffe Labs is India's fastest growing <br />
           omnichannel Pan India diagnostics service <br />
            provider having its services in 220+ cities <br />
             through a network of 80+ owned advanced <br />
             labs and 2000+ Collection Centers powered <br />
              by  home sample collection across India<br />
We are on a mission to provide quality <br />
 healthcare services at affordable rates <br />
  making diagnostics easily accessible and <br />
   convenient to one and all.</p>
   
        </div>
        <div className={styles.lastbanner2}>
        <h1 className={styles.lasth2}>Quick Links </h1>
        <p className={styles.lastp2}> Partner With Us <br />
FAQs <br />
About Us <br />
Our Labs <br />
Redcliffe Imaging <br />
ESG Practices <br />
Collection Centres</p>

        </div>
        <div className={styles.lastbanner3}>
          <h1 className={styles.lasth3}>Follow us on</h1>
          <ul className={styles.ulimg}>
            <li> <Image src="/instagram.png" height="40" width="40"></Image> </li>
            <li><Image src="/face.png" height="40" width="40"></Image> </li>
            <li><Image src="/x.png" height="40" width="40"></Image> </li>
            <li><Image src="/in.png" height="40" width="40"></Image> </li>
            <li><Image src="/youtube.png" height="40" width="40"></Image> </li>
          </ul>
        </div>
        <div className={styles.lastbanner4}>
        <h1 className={styles.lasth4}>Connect with us</h1>
        <Image src="/message.png" height="40" width="40" className={styles.lastimg11}></Image>

        <p className={styles.lastp4}>care@redcliffelabs.com</p>


        <Image src="/contact.png" height="40" width="40" className={styles.c11}></Image>
        
        <p className={styles.lastp5}>898 898 0606</p>


        <Image src="/location.png" height="40" width="40" className={styles.c12}></Image>
        
        <p className={styles.lastp6}>Corporate Address: H 55, <br />
         Electronic City, H Block, Sector 63, <br />
          Noida, Uttar Pradesh 201301</p>
        
        </div>
        <div className={styles.lastbanner5}></div>
      </div>
      
    </>
  );
}
